name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to the latest version
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r source/requirements/requirements.txt

    - name: Run Python script
      run: python source/py/now2.py

    - name: Upload M3U8 playlist
      uses: actions/upload-artifact@v3  # Updated to the latest version
      with:
        name: m3u8-playlist
        path: playlist2.m3u8  # New file path
