name: Convert JSON to M3U8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r source/requirements/requirements.txt

    - name: Run conversion script
      run: python source/py/convert_json_to_m3u8.py

    - name: Commit and push M3U8 playlist
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add source/json/test.m3u8
        git commit -m 'Add generated test.m3u8'
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
