name: Import

on:
  schedule:
    - cron: '03 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "nowtvtr bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests streamlink

      - name: fetch content nowtvtr
        run: |
          final_url=$(python3 source/now.py)
          echo "erstrm=${final_url}" >> $GITHUB_ENV
          dastrm=$(echo $final_url | sed 's/nowtv-live-ad.ercdn.net\/nowtv\/playlist.m3u8/nowtv.daioncdn.net\/nowtv\/nowtv.m3u8/')
          echo "dastrm=${dastrm}" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          erstrm=${erstrm}
          dastrm=${dastrm}
          sed -i "\|ercdn.net/nowtv| c $erstrm" playlist.m3u8
          sed -i "\|daioncdn.net/nowtv| c $dastrm" playlist.m3u8
          sed -i "\|ercdn.net/nowtv| c $erstrm" result/List/playlist.m3u8
          sed -i "\|daioncdn.net/nowtv| c $dastrm" result/List/playlist.m3u8

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add playlist.m3u8 result/List/playlist.m3u8
          git commit -m "nowtvtr updated"
          git push
