name: Uni

on:
  schedule:
    - cron: '0 */1 * * *'  # Einmal stündlich ausführen
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r source/requirements/requirements.txt
      - name: Download cookies
        run: |
          echo "${{ secrets.COOKIES }}" > cookies.txt
      - name: Move untracked files
        run: |
          mkdir -p temp_untracked
          mv result/List/uni/best/*.m3u8 temp_untracked/
          mv result/List/uni/*.m3u8 temp_untracked/
      - name: Execute Python script 
        run: python source/py/uni.py source/json/config.json
      - name: Commit and push files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "your-email@example.com"
          git config --local user.name "master bot"
          git pull origin main
          git add -A
          git commit -m "Update"
          git push origin main
      - name: Restore untracked files
        run: |
          mv temp_untracked/*.m3u8 result/List/uni/
          mv temp_untracked/best/*.m3u8 result/List/uni/best/
